title: <Laura Glastra> # your name (or website title) here
logo: "/images/IMG_6574.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student of Physical Oceanography 
  <br><br>
  URI Graduate School of Oceanography
  <br><br>
  <a href="https://www.linkedin.com/in/laura-glastra/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
